### ISSUE TITLE
Update Rate Limit Timeout

### ISSUE THREAD

**Issue by yashash1511** [nathanielop/achievements#11]
![image](https://user-images.githubusercontent.com/89068816/182891249-5458140c-46a9-49c9-bf51-a2acf54112cb.png)

on `bash pullshark` after around 50PR's it got rate limited for me 

maybe increasing the timeout would help?

**Comment by nathanielop** [comment]
Thank you for pointing this out, I personally hadn't tested it with 40s yet so wasn't sure whether or not it worked. I returned the timeout to the previous 1m value which worked for me when I did it. Let me known if you have any further issues.

**Comment by yashash1511** [comment]
![image](https://user-images.githubusercontent.com/89068816/182911517-00b86f61-896f-44c2-b56c-78a29e0d8009.png)

`pull request create failed: GraphQL: was submitted too quickly (createPullRequest)` even after the timeout was updated to 60s for me :(

**Comment by nathanielop** [comment]
Hmm... that's strange. I'll take a look around in a bit and update the timeout so hopefully you don't hit this again.
