### ISSUE TITLE
Some improvements and fixes 

### ISSUE THREAD

**Issue by MasterPi-2124** [nathanielop/achievements#7]
Hi, I saw your code and I am interested in it, but it contains some errors and I just fixed some of those. Can you take a look at it?
https://github.com/MasterPi-2124/achievements

The repo created in bin/setup is private, so I think github won't count that to the achievements. Instead, I make commits and prs straight into the main repo.

**Comment by nathanielop** [comment]
Yeah I took a quick peek and looks pretty good, if you want to open a PR against this repo I can merge it tonight. 

As far as the private repository goes, private repository achievements count so long as you have the "Show private contributions setting enabled on your github account", as referenced [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/showing-your-private-contributions-and-achievements-on-your-profile)

Thanks for ironing out the setup stuff, it was the last hurdle that this repo really had before being usable! =)

After merge I'll go in and update the README to reflect the new flow.

**Comment by MasterPi-2124** [comment]
hi, 20s is set accidentally :)). I will change that back to 40 50s. About our code, I think that both you and I are testing to make it work, for example in P-E file I see that we have different approaches. I think we just keep testing ourselves before marking as done and then merging. For now I think we can keep the discussion here, or go to https://github.com/Schweinepriester/github-profile-achievements and discuss with @Schweinepriester

**Comment by nathanielop** [comment]
Works for me either way, while I haven't pushed the changes up to this I intend to make similar changes to pair extraordinaire after testing of my initial approach proved that my assumption it was based purely on commits was wrong. However, I agree it's probably best to go at it separately and then merge when we have the optimal solution. We can continue discussion at the linked discussion.

**Comment by nathanielop** [comment]
Stale, although I've incorporated improvements made from your version into mine where possible, along with proper citation, thanks for taking time to help out!
