### ISSUE TITLE
GraphQL: Could not resolve to a Repository

### ISSUE THREAD

**Issue by WhoisMonesh** [nathanielop/achievements#89]
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
GraphQL: Could not resolve to a Repository with the name 'WhoisMonesh/achievements'. (repository)
GraphQL: Could not resolve to a Repository with the name 'WhoisMonesh/achievements'. (repository)
<img width="564" alt="Screenshot 2024-12-18 at 10 08 37 AM" src="https://github.com/user-attachments/assets/35a260f1-b23c-4ab6-9443-6319af2b9f33" />

**Comment by nathanielop** [comment]
This is an issue with the github CLI, not this repository, if the issue persists and the forked repository exists and your internet is working, then open the issue with the github cli package. Thanks.
