### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by devkennyy** [nathanielop/achievements#9]
I'm not very familiar with shell, how am I supposed to run the scripts after meeting the pre requisites?

**Comment by nathanielop** [comment]
Sorry about this, should've added both more information in the README and also have responded quicker. You're going to want to fork this repository, set up a folder on your computer called achievements or whatever you want, then you're going to want to go into that and set the git upstream to be the forked repository that you own, once this is setup, you should be able to run the scripts mentioned without issue. A rough guide of how to get to this point through the terminal;

```
cd ~/Desktop
mkdir achievements
cd achievements
git init
git remote add origin git@github.com:[YOUR USERNAME HERE]/[YOUR FORKED REPOSITORY NAME HERE].git
```

At this point you can then run `bash bin/quickdraw` or whatnot and it should work as expected.

**Comment by devkennyy** [comment]
> Sorry about this, should've added both more information in the README and also have responded quicker. 

Don't worry about it, thank you so much!
